### ISSUE TITLE
[Brave browser] "Caption this video" doesn't do a thing.

### ISSUE THREAD

**Issue by Jonahgay** [YouCap/Youcap-Extension#15]
When i open a YouTube link the extension logo gives color on the top right corner.
I also notice the logo on the video player under the time line, although i cannot interact with that button.

Opening the extension button, I click "_Caption this video_", the button does not do anything when clicked once or many times.

**Comment by JamesEConnor** [comment]
The button will only be interactable if there are captions available for the video (there are a couple of things in the works to make this clearer, such as #12). I was unable to reproduce the issue with the "Caption this video" button not working. Can you give some more specifics about your browser and the video you tried it on?

**Comment by Jonahgay** [comment]
> The button will only be interactable if there are captions available for the video (there are a couple of things in the works to make this clearer, such as #12). I was unable to reproduce the issue with the "Caption this video" button not working. Can you give some more specifics about your browser and the video you tried it on?

1. Specifics about my browser.
i have Brave v1.18.70 official installation

2. Videos i tried it on
https://www.youtube.com/watch?v=gOQNRvJbpmk and https://www.youtube.com/watch?v=1pLYofDgGSI

**Comment by JamesEConnor** [comment]
> 1. Specifics about my browser.
>    i have Brave v1.18.70 official installation
> 2. Videos i tried it on
>    https://www.youtube.com/watch?v=gOQNRvJbpmk and https://www.youtube.com/watch?v=1pLYofDgGSI

I tried Brave v1.18.70 with both links and it worked perfectly fine. Can you see if there are any errors being thrown in the devtools console?

**Comment by Jonahgay** [comment]
![consol1](https://user-images.githubusercontent.com/16048625/102666943-6fae8c80-4188-11eb-9557-bcd3c218fe9e.png)
![consol2](https://user-images.githubusercontent.com/16048625/102666947-72a97d00-4188-11eb-827c-6e4a73e4b386.png)
![consol3](https://user-images.githubusercontent.com/16048625/102666953-750bd700-4188-11eb-8e4d-6446bfacb034.png)

There you go.

**Comment by JamesEConnor** [comment]
After a bit more work, I think I was able to narrow down the issue. When the popup window requests the tabs to obtain the video URL, it uses lastFocusedWindow to filter all of the tabs. I'm going to try using the currentWindow filter instead and see if that fixes the issue.
