### ISSUE TITLE
Redirect www.youcap.video to youcap.video

### ISSUE THREAD

**Issue by ajayyy** [YouCap/Youcap-Extension#2]
It seems to break Google login

**Comment by JamesEConnor** [comment]
Turned out to be a problem with the Google API console. Can you confirm it's fixed on your end?

**Comment by ajayyy** [comment]
Seems fixed, but it still has a different session than the naked domain, so you have to log in twice.

**Comment by JamesEConnor** [comment]
I believe it's been resolved with a redirect? Give it another shot.

**Comment by ajayyy** [comment]
Looks good now!
